import type { Action } from '../types.js';

export const advancedCombosA: Action[] = [
  { id: 'a-1-2-5-2', type: 'combo', label: '1-2-5-2', description: 'Jab - Cross - Lead Uppercut - Cross', difficulty: 'advanced', durationMs: 2000 },
  { id: 'a-1-2-3-4-2', type: 'combo', label: '1-2-3-4-2', description: 'Jab - Cross - Lead Hook - Rear Hook - Cross', difficulty: 'advanced', durationMs: 2200 },
  { id: 'a-5-6-2', type: 'combo', label: '5-6-2', description: 'Lead Uppercut - Rear Uppercut - Cross', difficulty: 'advanced', durationMs: 1500 },
  { id: 'a-3-6-3-2', type: 'combo', label: '3-6-3-2', description: 'Lead Hook - Rear Uppercut - Lead Hook - Cross', difficulty: 'advanced', durationMs: 2000 },
  { id: 'a-1-6-3-2', type: 'combo', label: '1-6-3-2', description: 'Jab - Rear Uppercut - Lead Hook - Cross', difficulty: 'advanced', durationMs: 2000 },
  { id: 'a-5-2', type: 'combo', label: '5-2', description: 'Lead Uppercut - Cross', difficulty: 'advanced', durationMs: 1000 },
  { id: 'a-6-5-2', type: 'combo', label: '6-5-2', description: 'Rear Uppercut - Lead Uppercut - Cross', difficulty: 'advanced', durationMs: 1500 },
  { id: 'a-1-2-5-6', type: 'combo', label: '1-2-5-6', description: 'Jab - Cross - Lead Uppercut - Rear Uppercut', difficulty: 'advanced', durationMs: 2000 },
  { id: 'a-3-6-3', type: 'combo', label: '3-6-3', description: 'Lead Hook - Rear Uppercut - Lead Hook', difficulty: 'advanced', durationMs: 1500 },
  { id: 'a-1-6-5-2', type: 'combo', label: '1-6-5-2', description: 'Jab - Rear Uppercut - Lead Uppercut - Cross', difficulty: 'advanced', durationMs: 2000 },
  { id: 'a-2-1-6-2', type: 'combo', label: '2-1-6-2', description: 'Cross - Jab (pull) - Rear Uppercut - Cross', difficulty: 'advanced', durationMs: 2000 },
  { id: 'a-1-2-3-2-5', type: 'combo', label: '1-2-3-2-5', description: 'Jab - Cross - Hook - Cross - Lead Uppercut', difficulty: 'advanced', durationMs: 2200 },
  { id: 'a-3-3-2', type: 'combo', label: '3-3-2', description: 'Double Lead Hook - Cross', difficulty: 'advanced', durationMs: 1500 },
  { id: 'a-1-1-2-5', type: 'combo', label: '1-1-2-5', description: 'Double Jab - Cross - Lead Uppercut (step in)', difficulty: 'advanced', durationMs: 2000 },
  { id: 'a-6-2-3-2', type: 'combo', label: '6-2-3-2', description: 'Rear Uppercut - Cross - Lead Hook - Cross', difficulty: 'advanced', durationMs: 2000 },
];

export const advancedCombosB: Action[] = [
  { id: 'a-slip-1-2', type: 'combo', label: 'SLIP-1-2', description: 'Slip - Jab - Cross', difficulty: 'advanced', durationMs: 1800 },
  { id: 'a-roll-3-2', type: 'combo', label: 'ROLL-3-2', description: 'Roll - Lead Hook - Cross', difficulty: 'advanced', durationMs: 1800 },
  { id: 'a-1-2-b3-b2', type: 'combo', label: '1-2-B3-B2', description: 'Jab - Cross - Body Hook - Body Cross', difficulty: 'advanced', durationMs: 2000 },
  { id: 'a-1-b2-3-2', type: 'combo', label: '1-B2-3-2', description: 'Jab - Body Cross - Lead Hook - Cross', difficulty: 'advanced', durationMs: 2000 },
  { id: 'a-1-2-3-b2-3-2', type: 'combo', label: '1-2-3-B2-3-2', description: 'Jab - Cross - Hook - Body Cross - Hook - Cross', difficulty: 'advanced', durationMs: 3000 },
  { id: 'a-slip-3-6-3-2', type: 'combo', label: 'SLIP-3-6-3-2', description: 'Slip - Lead Hook - Rear Uppercut - Lead Hook - Cross', difficulty: 'advanced', durationMs: 2800 },
  { id: 'a-b1-b2', type: 'combo', label: 'B1-B2', description: 'Body Jab - Body Cross', difficulty: 'advanced', durationMs: 1000 },
  { id: 'a-1-b2-b3-2', type: 'combo', label: '1-B2-B3-2', description: 'Jab - Body Cross - Body Hook - Cross', difficulty: 'advanced', durationMs: 2000 },
  { id: 'a-roll-6-3-2', type: 'combo', label: 'ROLL-6-3-2', description: 'Roll - Rear Uppercut - Lead Hook - Cross', difficulty: 'advanced', durationMs: 2200 },
  { id: 'a-slip-slip-1-2-3', type: 'combo', label: 'SLIP-SLIP-1-2-3', description: 'Double Slip - Jab - Cross - Hook', difficulty: 'advanced', durationMs: 2600 },
  { id: 'a-1-2-b1-b2-3-2', type: 'combo', label: '1-2-B1-B2-3-2', description: 'Jab - Cross - Body Jab - Body Cross - Hook - Cross', difficulty: 'advanced', durationMs: 3000 },
  { id: 'a-1-2-3-roll-left-3-2', type: 'combo', label: '1-2-3-ROLL-LEFT-3-2', description: 'Jab - Cross - Hook - Roll - Hook - Cross', difficulty: 'advanced', durationMs: 3200 },
  { id: 'a-1-2-3-roll-right-3-2', type: 'combo', label: '1-2-3-ROLL-RIGHT-3-2', description: 'Jab - Cross - Hook - Roll - Hook - Cross', difficulty: 'advanced', durationMs: 3200 },
  { id: 'a-5-2-3-2', type: 'combo', label: '5-2-3-2', description: 'Lead Uppercut - Cross - Lead Hook - Cross', difficulty: 'advanced', durationMs: 2000 },
  { id: 'a-1-2-3-4-5-6', type: 'combo', label: '1-2-3-4-5-6', description: 'Jab - Cross - Lead Hook - Rear Hook - Lead Upper - Rear Upper', difficulty: 'advanced', durationMs: 3000 },
  { id: 'a-feint-1-2-3', type: 'combo', label: 'FEINT-1-2-3', description: 'Feint - Jab - Cross - Hook (commit to body)', difficulty: 'advanced', durationMs: 2200 },
  { id: 'a-1-b3-2', type: 'combo', label: '1-B3-2', description: 'Jab - Body Hook - Cross (step to the outside)', difficulty: 'advanced', durationMs: 1500 },
  { id: 'a-slip-2-5-2', type: 'combo', label: 'SLIP-2-5-2', description: 'Slip - Cross - Lead Uppercut - Cross', difficulty: 'advanced', durationMs: 2200 },
  { id: 'a-pivot-left-3-2', type: 'combo', label: 'PIVOT-LEFT-3-2', description: 'Jab - Pivot left outside - Lead Hook - Cross', difficulty: 'advanced', durationMs: 2200 },
  { id: 'a-pivot-right-3-2', type: 'combo', label: 'PIVOT-RIGHT-3-2', description: 'Jab - Pivot right outside - Lead Hook - Cross', difficulty: 'advanced', durationMs: 2200 },
  { id: 'a-doublebody-5-5-2', type: 'combo', label: 'B5-B5-2', description: 'Double Lead Uppercut to body - Cross (close range)', difficulty: 'advanced', durationMs: 1500 },
];

export const proCombos: Action[] = [
  { id: 'p-1-2-0-2-3', type: 'combo', label: '1-2-STEP-2-3', description: 'Jab - Cross - Step off-line - Cross - Lead Hook (counter focus)', difficulty: 'pro', durationMs: 3000 },
  { id: 'p-feint-1-2-6-3', type: 'combo', label: 'FEINT-1-2-6-3', description: 'Feint - Jab - Cross - Rear Uppercut - Lead Hook (finish)', difficulty: 'pro', durationMs: 2800 },
  { id: 'p-1-2-3-overhand', type: 'combo', label: '1-2-3-OVERHAND', description: 'Jab - Cross - Lead Hook - Overhand Right (timed behind cross)', difficulty: 'pro', durationMs: 2200 },
  { id: 'p-slip-counter-2-5', type: 'combo', label: 'SLIP-COUNTER-2-5', description: 'Slip inside - Counter Cross - Lead Uppercut (close-range counter)', difficulty: 'pro', durationMs: 2000 },
  { id: 'p-4-3-2-6', type: 'combo', label: '4-3-2-6', description: 'Rear Hook - Lead Hook - Cross - Rear Uppercut (head-body mix)', difficulty: 'pro', durationMs: 2200 },
  { id: 'p-1-b2-1-2', type: 'combo', label: '1-B2-1-2', description: 'Jab - Body Cross - Quick Jab - Cross to head (change level)', difficulty: 'pro', durationMs: 2200 },
  { id: 'p-1-1-2-5-6', type: 'combo', label: '1-1-2-5-6', description: 'Double Jab - Cross - Lead Uppercut - Rear Uppercut (trap opponent)', difficulty: 'pro', durationMs: 2500 },
  { id: 'p-pivot-6-3-2', type: 'combo', label: 'PIVOT-6-3-2', description: 'Jab - Pivot outside - Rear Uppercut - Lead Hook - Cross', difficulty: 'pro', durationMs: 2800 },
  { id: 'p-feint-slip-3-2-5', type: 'combo', label: 'FEINT-SLIP-3-2-5', description: 'Feint - Slip - Lead Hook - Cross - Lead Uppercut (counter/finish)', difficulty: 'pro', durationMs: 2800 },
  { id: 'p-2-3-2-throw-6', type: 'combo', label: '2-3-2-THROW-6', description: 'Cross - Hook - Cross - Throw weight forward - Rear Uppercut', difficulty: 'pro', durationMs: 2800 },
  { id: 'p-overhand-1-2-3', type: 'combo', label: 'OVERHAND-1-2-3', description: 'Overhand Right - Jab - Cross - Lead Hook (use to open guard)', difficulty: 'pro', durationMs: 2200 },
  { id: 'p-body-head-switch-1-b3-3-2', type: 'combo', label: '1-B3-3-2', description: 'Jab - Body Hook - Lead Hook to head - Cross (switch levels twice)', difficulty: 'pro', durationMs: 2200 },
  { id: 'p-clinch-5-2', type: 'combo', label: 'CLINCH-5-2', description: 'Step in to clinch - Lead Uppercut - Break - Cross (short-range sequence)', difficulty: 'pro', durationMs: 2500 },
  { id: 'p-1-2-feint-4-2', type: 'combo', label: '1-2-FEINT-4-2', description: 'Jab - Cross - Feint hook - Rear Hook - Cross (create openings)', difficulty: 'pro', durationMs: 2800 },
  { id: 'p-slip-roll-6-2-3', type: 'combo', label: 'SLIP-ROLL-6-2-3', description: 'Slip outside - Roll under - Rear Uppercut - Cross - Lead Hook', difficulty: 'pro', durationMs: 3200 },
  { id: 'p-double-overhand-2-5-2', type: 'combo', label: 'DOUBLE-OVERHAND-2-5-2', description: 'Double Overhand - Cross - Lead Uppercut - Cross (power sequences)', difficulty: 'pro', durationMs: 2800 },
  { id: 'p-1-2-quickstep-out-3', type: 'combo', label: '1-2-STEP-OUT-3', description: 'Jab - Cross - Quick step out to angle - Lead Hook (angulation finish)', difficulty: 'pro', durationMs: 2500 },
  { id: 'p-counter-pivot-2-6-3', type: 'combo', label: 'COUNTER-PIVOT-2-6-3', description: 'Counter Cross - Pivot - Rear Uppercut - Lead Hook (counter & reposition)', difficulty: 'pro', durationMs: 2800 },
];
