/**
 * Generated by scripts/generate-coach-registry.mjs — do not edit by hand.
 * Re-run: pnpm --filter @boxing-coach/mobile run generate:coach-registry
 */
export const coachRegistry: Record<string, number> = {

};
